/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAnalyticsRouteImport } from './routes/teacher.analytics'
import { Route as TeacherClassIdRouteImport } from './routes/teacher.class.$id'
import { Route as TeacherClassIdGradeRouteImport } from './routes/teacher.class.$id.grade'
import { Route as TeacherClassIdAssessmentAssessmentIdRouteImport } from './routes/teacher.class.$id.assessment.$assessmentId'
import { Route as TeacherClassIdStudentStudentIdRouteImport } from './routes/teacher.class.$id.student.$studentId'
import { Route as ClassIdRouteImport } from './routes/class.$id'
import { Route as ClassIdIndexRouteImport } from './routes/class.$id.index'
import { Route as ClassIdUploadRouteImport } from './routes/class.$id.upload'
import { Route as ClassIdAssignmentsRouteImport } from './routes/class.$id.assignments'
import { Route as ClassIdAssignmentAssignmentIdRouteImport } from './routes/class.$id.assignment.$assignmentId'
import { Route as ClassIdSetSetIdRouteImport } from './routes/class.$id.set.$setId'
import { Route as ClassIdSetSetIdIndexRouteImport } from './routes/class.$id.set.$setId.index'
import { Route as ClassIdSetSetIdAudioRouteImport } from './routes/class.$id.set.$setId.audio'
import { Route as ClassIdSetSetIdFlashcardsRouteImport } from './routes/class.$id.set.$setId.flashcards'
import { Route as ClassIdSetSetIdQuizRouteImport } from './routes/class.$id.set.$setId.quiz'
import { Route as ClassIdSetSetIdClassicalRouteImport } from './routes/class.$id.set.$setId.classical'
import { Route as ClassIdSetSetIdSpatialRouteImport } from './routes/class.$id.set.$setId.spatial'
import { Route as MeetingIdRouteImport } from './routes/meeting.$id'
import { Route as MeetingIdIndexRouteImport } from './routes/meeting.$id.index'
import { Route as MeetingIdUploadRouteImport } from './routes/meeting.$id.upload'
import { Route as MeetingIdSessionSessionIdRouteImport } from './routes/meeting.$id.session.$sessionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const ArchivedRoute = ArchivedRouteImport.update({ id: '/archived', path: '/archived', getParentRoute: () => rootRouteImport } as any)
const ComingSoonRoute = ComingSoonRouteImport.update({ id: '/coming-soon', path: '/coming-soon', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const ProfileRoute = ProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => rootRouteImport } as any)
const SignupRoute = SignupRouteImport.update({ id: '/signup', path: '/signup', getParentRoute: () => rootRouteImport } as any)
const NotesRoute = NotesRouteImport.update({ id: '/notes', path: '/notes', getParentRoute: () => rootRouteImport } as any)
const MeetingsRoute = MeetingsRouteImport.update({ id: '/meetings', path: '/meetings', getParentRoute: () => rootRouteImport } as any)
const ProjectsRoute = ProjectsRouteImport.update({ id: '/projects', path: '/projects', getParentRoute: () => rootRouteImport } as any)
const ProjectIdRoute = ProjectIdRouteImport.update({ id: '/project/$id', path: '/project/$id', getParentRoute: () => rootRouteImport } as any)
const TeacherRoute = TeacherRouteImport.update({ id: '/teacher', path: '/teacher', getParentRoute: () => rootRouteImport } as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({ id: '/teacher/', path: '/', getParentRoute: () => TeacherRoute } as any)
const TeacherAnalyticsRoute = TeacherAnalyticsRouteImport.update({ id: '/teacher/analytics', path: '/analytics', getParentRoute: () => TeacherRoute } as any)
const TeacherClassIdRoute = TeacherClassIdRouteImport.update({ id: '/teacher/class/$id', path: '/class/$id', getParentRoute: () => TeacherRoute } as any)
const TeacherClassIdGradeRoute = TeacherClassIdGradeRouteImport.update({ id: '/teacher/class/$id/grade', path: '/class/$id/grade', getParentRoute: () => TeacherRoute } as any)
const TeacherClassIdAssessmentAssessmentIdRoute = TeacherClassIdAssessmentAssessmentIdRouteImport.update({ id: '/teacher/class/$id/assessment/$assessmentId', path: '/class/$id/assessment/$assessmentId', getParentRoute: () => TeacherRoute } as any)
const TeacherClassIdStudentStudentIdRoute = TeacherClassIdStudentStudentIdRouteImport.update({ id: '/teacher/class/$id/student/$studentId', path: '/class/$id/student/$studentId', getParentRoute: () => TeacherRoute } as any)
const ClassIdRoute = ClassIdRouteImport.update({ id: '/class/$id', path: '/class/$id', getParentRoute: () => rootRouteImport } as any)
const ClassIdIndexRoute = ClassIdIndexRouteImport.update({ id: '/class/$id/', path: '/', getParentRoute: () => ClassIdRoute } as any)
const ClassIdUploadRoute = ClassIdUploadRouteImport.update({ id: '/class/$id/upload', path: '/upload', getParentRoute: () => ClassIdRoute } as any)
const ClassIdAssignmentsRoute = ClassIdAssignmentsRouteImport.update({ id: '/class/$id/assignments', path: '/assignments', getParentRoute: () => ClassIdRoute } as any)
const ClassIdAssignmentAssignmentIdRoute = ClassIdAssignmentAssignmentIdRouteImport.update({ id: '/class/$id/assignment/$assignmentId', path: '/assignment/$assignmentId', getParentRoute: () => ClassIdRoute } as any)
const ClassIdSetSetIdRoute = ClassIdSetSetIdRouteImport.update({ id: '/class/$id/set/$setId', path: '/set/$setId', getParentRoute: () => ClassIdRoute } as any)
const ClassIdSetSetIdIndexRoute = ClassIdSetSetIdIndexRouteImport.update({ id: '/class/$id/set/$setId/', path: '/', getParentRoute: () => ClassIdSetSetIdRoute } as any)
const ClassIdSetSetIdAudioRoute = ClassIdSetSetIdAudioRouteImport.update({ id: '/class/$id/set/$setId/audio', path: '/audio', getParentRoute: () => ClassIdSetSetIdRoute } as any)
const ClassIdSetSetIdFlashcardsRoute = ClassIdSetSetIdFlashcardsRouteImport.update({ id: '/class/$id/set/$setId/flashcards', path: '/flashcards', getParentRoute: () => ClassIdSetSetIdRoute } as any)
const ClassIdSetSetIdQuizRoute = ClassIdSetSetIdQuizRouteImport.update({ id: '/class/$id/set/$setId/quiz', path: '/quiz', getParentRoute: () => ClassIdSetSetIdRoute } as any)
const ClassIdSetSetIdClassicalRoute = ClassIdSetSetIdClassicalRouteImport.update({ id: '/class/$id/set/$setId/classical', path: '/classical', getParentRoute: () => ClassIdSetSetIdRoute } as any)
const ClassIdSetSetIdSpatialRoute = ClassIdSetSetIdSpatialRouteImport.update({ id: '/class/$id/set/$setId/spatial', path: '/spatial', getParentRoute: () => ClassIdSetSetIdRoute } as any)
const MeetingIdRoute = MeetingIdRouteImport.update({ id: '/meeting/$id', path: '/meeting/$id', getParentRoute: () => rootRouteImport } as any)
const MeetingIdIndexRoute = MeetingIdIndexRouteImport.update({ id: '/meeting/$id/', path: '/', getParentRoute: () => MeetingIdRoute } as any)
const MeetingIdUploadRoute = MeetingIdUploadRouteImport.update({ id: '/meeting/$id/upload', path: '/upload', getParentRoute: () => MeetingIdRoute } as any)
const MeetingIdSessionSessionIdRoute = MeetingIdSessionSessionIdRouteImport.update({ id: '/meeting/$id/session/$sessionId', path: '/session/$sessionId', getParentRoute: () => MeetingIdRoute } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({ id: '/api/auth/$', path: '/api/auth/$', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/notes': typeof NotesRoute
  '/meetings': typeof MeetingsRoute
  '/projects': typeof ProjectsRoute
  '/project/$id': typeof ProjectIdRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/class/$id': typeof TeacherClassIdRoute
  '/teacher/class/$id/grade': typeof TeacherClassIdGradeRoute
  '/teacher/class/$id/assessment/$assessmentId': typeof TeacherClassIdAssessmentAssessmentIdRoute
  '/class/$id': typeof ClassIdRouteWithChildren
  '/class/$id/': typeof ClassIdIndexRoute
  '/class/$id/upload': typeof ClassIdUploadRoute
  '/class/$id/assignments': typeof ClassIdAssignmentsRoute
  '/class/$id/assignment/$assignmentId': typeof ClassIdAssignmentAssignmentIdRoute
  '/class/$id/set/$setId': typeof ClassIdSetSetIdRouteWithChildren
  '/class/$id/set/$setId/': typeof ClassIdSetSetIdIndexRoute
  '/class/$id/set/$setId/audio': typeof ClassIdSetSetIdAudioRoute
  '/class/$id/set/$setId/flashcards': typeof ClassIdSetSetIdFlashcardsRoute
  '/class/$id/set/$setId/quiz': typeof ClassIdSetSetIdQuizRoute
  '/class/$id/set/$setId/classical': typeof ClassIdSetSetIdClassicalRoute
  '/class/$id/set/$setId/spatial': typeof ClassIdSetSetIdSpatialRoute
  '/meeting/$id': typeof MeetingIdRouteWithChildren
  '/meeting/$id/': typeof MeetingIdIndexRoute
  '/meeting/$id/upload': typeof MeetingIdUploadRoute
  '/meeting/$id/session/$sessionId': typeof MeetingIdSessionSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/notes': typeof NotesRoute
  '/meetings': typeof MeetingsRoute
  '/projects': typeof ProjectsRoute
  '/project/$id': typeof ProjectIdRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/class/$id': typeof TeacherClassIdRoute
  '/teacher/class/$id/grade': typeof TeacherClassIdGradeRoute
  '/teacher/class/$id/assessment/$assessmentId': typeof TeacherClassIdAssessmentAssessmentIdRoute
  '/class/$id': typeof ClassIdIndexRoute
  '/class/$id/upload': typeof ClassIdUploadRoute
  '/class/$id/assignments': typeof ClassIdAssignmentsRoute
  '/class/$id/assignment/$assignmentId': typeof ClassIdAssignmentAssignmentIdRoute
  '/class/$id/set/$setId': typeof ClassIdSetSetIdIndexRoute
  '/class/$id/set/$setId/audio': typeof ClassIdSetSetIdAudioRoute
  '/class/$id/set/$setId/flashcards': typeof ClassIdSetSetIdFlashcardsRoute
  '/class/$id/set/$setId/quiz': typeof ClassIdSetSetIdQuizRoute
  '/class/$id/set/$setId/classical': typeof ClassIdSetSetIdClassicalRoute
  '/class/$id/set/$setId/spatial': typeof ClassIdSetSetIdSpatialRoute
  '/meeting/$id': typeof MeetingIdIndexRoute
  '/meeting/$id/upload': typeof MeetingIdUploadRoute
  '/meeting/$id/session/$sessionId': typeof MeetingIdSessionSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/notes': typeof NotesRoute
  '/meetings': typeof MeetingsRoute
  '/projects': typeof ProjectsRoute
  '/project/$id': typeof ProjectIdRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/class/$id': typeof TeacherClassIdRoute
  '/teacher/class/$id/grade': typeof TeacherClassIdGradeRoute
  '/teacher/class/$id/assessment/$assessmentId': typeof TeacherClassIdAssessmentAssessmentIdRoute
  '/class/$id': typeof ClassIdRouteWithChildren
  '/class/$id/': typeof ClassIdIndexRoute
  '/class/$id/upload': typeof ClassIdUploadRoute
  '/class/$id/assignments': typeof ClassIdAssignmentsRoute
  '/class/$id/assignment/$assignmentId': typeof ClassIdAssignmentAssignmentIdRoute
  '/class/$id/set/$setId': typeof ClassIdSetSetIdRouteWithChildren
  '/class/$id/set/$setId/': typeof ClassIdSetSetIdIndexRoute
  '/class/$id/set/$setId/audio': typeof ClassIdSetSetIdAudioRoute
  '/class/$id/set/$setId/flashcards': typeof ClassIdSetSetIdFlashcardsRoute
  '/class/$id/set/$setId/quiz': typeof ClassIdSetSetIdQuizRoute
  '/class/$id/set/$setId/classical': typeof ClassIdSetSetIdClassicalRoute
  '/class/$id/set/$setId/spatial': typeof ClassIdSetSetIdSpatialRoute
  '/meeting/$id': typeof MeetingIdRouteWithChildren
  '/meeting/$id/': typeof MeetingIdIndexRoute
  '/meeting/$id/upload': typeof MeetingIdUploadRoute
  '/meeting/$id/session/$sessionId': typeof MeetingIdSessionSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archived'
    | '/coming-soon'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/notes'
    | '/meetings'
    | '/projects'
    | '/project/$id'
    | '/teacher'
    | '/teacher/analytics'
    | '/teacher/class/$id'
    | '/teacher/class/$id/grade'
    | '/teacher/class/$id/assessment/$assessmentId'
    | '/class/$id'
    | '/class/$id/'
    | '/class/$id/upload'
    | '/class/$id/assignments'
    | '/class/$id/assignment/$assignmentId'
    | '/class/$id/set/$setId'
    | '/class/$id/set/$setId/'
    | '/class/$id/set/$setId/audio'
    | '/class/$id/set/$setId/flashcards'
    | '/class/$id/set/$setId/quiz'
    | '/class/$id/set/$setId/classical'
    | '/class/$id/set/$setId/spatial'
    | '/meeting/$id'
    | '/meeting/$id/'
    | '/meeting/$id/upload'
    | '/meeting/$id/session/$sessionId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived'
    | '/coming-soon'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/notes'
    | '/meetings'
    | '/projects'
    | '/project/$id'
    | '/teacher'
    | '/teacher/analytics'
    | '/teacher/class/$id'
    | '/teacher/class/$id/grade'
    | '/teacher/class/$id/assessment/$assessmentId'
    | '/class/$id'
    | '/class/$id/upload'
    | '/class/$id/assignments'
    | '/class/$id/assignment/$assignmentId'
    | '/class/$id/set/$setId'
    | '/class/$id/set/$setId/audio'
    | '/class/$id/set/$setId/flashcards'
    | '/class/$id/set/$setId/quiz'
    | '/class/$id/set/$setId/classical'
    | '/class/$id/set/$setId/spatial'
    | '/meeting/$id'
    | '/meeting/$id/upload'
    | '/meeting/$id/session/$sessionId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/archived'
    | '/coming-soon'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/notes'
    | '/meetings'
    | '/projects'
    | '/project/$id'
    | '/teacher'
    | '/teacher/analytics'
    | '/teacher/class/$id'
    | '/teacher/class/$id/grade'
    | '/teacher/class/$id/assessment/$assessmentId'
    | '/class/$id'
    | '/class/$id/'
    | '/class/$id/upload'
    | '/class/$id/assignments'
    | '/class/$id/assignment/$assignmentId'
    | '/class/$id/set/$setId'
    | '/class/$id/set/$setId/'
    | '/class/$id/set/$setId/audio'
    | '/class/$id/set/$setId/flashcards'
    | '/class/$id/set/$setId/quiz'
    | '/class/$id/set/$setId/classical'
    | '/class/$id/set/$setId/spatial'
    | '/meeting/$id'
    | '/meeting/$id/'
    | '/meeting/$id/upload'
    | '/meeting/$id/session/$sessionId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedRoute: typeof ArchivedRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  NotesRoute: typeof NotesRoute
  MeetingsRoute: typeof MeetingsRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectIdRoute: typeof ProjectIdRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  ClassIdRoute: typeof ClassIdRouteWithChildren
  MeetingIdRoute: typeof MeetingIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/archived': { id: '/archived'; path: '/archived'; fullPath: '/archived'; preLoaderRoute: typeof ArchivedRouteImport; parentRoute: typeof rootRouteImport }
    '/coming-soon': { id: '/coming-soon'; path: '/coming-soon'; fullPath: '/coming-soon'; preLoaderRoute: typeof ComingSoonRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/profile': { id: '/profile'; path: '/profile'; fullPath: '/profile'; preLoaderRoute: typeof ProfileRouteImport; parentRoute: typeof rootRouteImport }
    '/signup': { id: '/signup'; path: '/signup'; fullPath: '/signup'; preLoaderRoute: typeof SignupRouteImport; parentRoute: typeof rootRouteImport }
    '/notes': { id: '/notes'; path: '/notes'; fullPath: '/notes'; preLoaderRoute: typeof NotesRouteImport; parentRoute: typeof rootRouteImport }
    '/meetings': { id: '/meetings'; path: '/meetings'; fullPath: '/meetings'; preLoaderRoute: typeof MeetingsRouteImport; parentRoute: typeof rootRouteImport }
    '/projects': { id: '/projects'; path: '/projects'; fullPath: '/projects'; preLoaderRoute: typeof ProjectsRouteImport; parentRoute: typeof rootRouteImport }
    '/project/$id': { id: '/project/$id'; path: '/project/$id'; fullPath: '/project/$id'; preLoaderRoute: typeof ProjectIdRouteImport; parentRoute: typeof rootRouteImport }
    '/teacher': { id: '/teacher'; path: '/teacher'; fullPath: '/teacher'; preLoaderRoute: typeof TeacherRouteImport; parentRoute: typeof rootRouteImport }
    '/teacher/analytics': { id: '/teacher/analytics'; path: '/teacher/analytics'; fullPath: '/teacher/analytics'; preLoaderRoute: typeof TeacherAnalyticsRouteImport; parentRoute: typeof rootRouteImport }
    '/teacher/class/$id': { id: '/teacher/class/$id'; path: '/teacher/class/$id'; fullPath: '/teacher/class/$id'; preLoaderRoute: typeof TeacherClassIdRouteImport; parentRoute: typeof rootRouteImport }
    '/teacher/class/$id/grade': { id: '/teacher/class/$id/grade'; path: '/teacher/class/$id/grade'; fullPath: '/teacher/class/$id/grade'; preLoaderRoute: typeof TeacherClassIdGradeRouteImport; parentRoute: typeof rootRouteImport }
    '/teacher/class/$id/assessment/$assessmentId': { id: '/teacher/class/$id/assessment/$assessmentId'; path: '/teacher/class/$id/assessment/$assessmentId'; fullPath: '/teacher/class/$id/assessment/$assessmentId'; preLoaderRoute: typeof TeacherClassIdAssessmentAssessmentIdRouteImport; parentRoute: typeof rootRouteImport }
    '/class/$id': { id: '/class/$id'; path: '/class/$id'; fullPath: '/class/$id'; preLoaderRoute: typeof ClassIdRouteImport; parentRoute: typeof rootRouteImport }
    '/class/$id/': { id: '/class/$id/'; path: '/'; fullPath: '/class/$id/'; preLoaderRoute: typeof ClassIdIndexRouteImport; parentRoute: typeof ClassIdRoute }
    '/class/$id/upload': { id: '/class/$id/upload'; path: '/upload'; fullPath: '/class/$id/upload'; preLoaderRoute: typeof ClassIdUploadRouteImport; parentRoute: typeof ClassIdRoute }
    '/class/$id/assignments': { id: '/class/$id/assignments'; path: '/assignments'; fullPath: '/class/$id/assignments'; preLoaderRoute: typeof ClassIdAssignmentsRouteImport; parentRoute: typeof ClassIdRoute }
    '/class/$id/assignment/$assignmentId': { id: '/class/$id/assignment/$assignmentId'; path: '/assignment/$assignmentId'; fullPath: '/class/$id/assignment/$assignmentId'; preLoaderRoute: typeof ClassIdAssignmentAssignmentIdRouteImport; parentRoute: typeof ClassIdRoute }
    '/class/$id/set/$setId': { id: '/class/$id/set/$setId'; path: '/set/$setId'; fullPath: '/class/$id/set/$setId'; preLoaderRoute: typeof ClassIdSetSetIdRouteImport; parentRoute: typeof ClassIdRoute }
    '/class/$id/set/$setId/': { id: '/class/$id/set/$setId/'; path: '/'; fullPath: '/class/$id/set/$setId/'; preLoaderRoute: typeof ClassIdSetSetIdIndexRouteImport; parentRoute: typeof ClassIdSetSetIdRoute }
    '/class/$id/set/$setId/audio': { id: '/class/$id/set/$setId/audio'; path: '/audio'; fullPath: '/class/$id/set/$setId/audio'; preLoaderRoute: typeof ClassIdSetSetIdAudioRouteImport; parentRoute: typeof ClassIdSetSetIdRoute }
    '/class/$id/set/$setId/flashcards': { id: '/class/$id/set/$setId/flashcards'; path: '/flashcards'; fullPath: '/class/$id/set/$setId/flashcards'; preLoaderRoute: typeof ClassIdSetSetIdFlashcardsRouteImport; parentRoute: typeof ClassIdSetSetIdRoute }
    '/class/$id/set/$setId/quiz': { id: '/class/$id/set/$setId/quiz'; path: '/quiz'; fullPath: '/class/$id/set/$setId/quiz'; preLoaderRoute: typeof ClassIdSetSetIdQuizRouteImport; parentRoute: typeof ClassIdSetSetIdRoute }
    '/class/$id/set/$setId/classical': { id: '/class/$id/set/$setId/classical'; path: '/classical'; fullPath: '/class/$id/set/$setId/classical'; preLoaderRoute: typeof ClassIdSetSetIdClassicalRouteImport; parentRoute: typeof ClassIdSetSetIdRoute }
    '/class/$id/set/$setId/spatial': { id: '/class/$id/set/$setId/spatial'; path: '/spatial'; fullPath: '/class/$id/set/$setId/spatial'; preLoaderRoute: typeof ClassIdSetSetIdSpatialRouteImport; parentRoute: typeof ClassIdSetSetIdRoute }
    '/meeting/$id': { id: '/meeting/$id'; path: '/meeting/$id'; fullPath: '/meeting/$id'; preLoaderRoute: typeof MeetingIdRouteImport; parentRoute: typeof rootRouteImport }
    '/meeting/$id/': { id: '/meeting/$id/'; path: '/'; fullPath: '/meeting/$id/'; preLoaderRoute: typeof MeetingIdIndexRouteImport; parentRoute: typeof MeetingIdRoute }
    '/meeting/$id/upload': { id: '/meeting/$id/upload'; path: '/upload'; fullPath: '/meeting/$id/upload'; preLoaderRoute: typeof MeetingIdUploadRouteImport; parentRoute: typeof MeetingIdRoute }
    '/meeting/$id/session/$sessionId': { id: '/meeting/$id/session/$sessionId'; path: '/session/$sessionId'; fullPath: '/meeting/$id/session/$sessionId'; preLoaderRoute: typeof MeetingIdSessionSessionIdRouteImport; parentRoute: typeof MeetingIdRoute }
    '/api/auth/$': { id: '/api/auth/$'; path: '/api/auth/$'; fullPath: '/api/auth/$'; preLoaderRoute: typeof ApiAuthSplatRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const ClassIdSetSetIdRouteWithChildren = ClassIdSetSetIdRoute._addFileChildren({
  ClassIdSetSetIdAudioRoute,
  ClassIdSetSetIdFlashcardsRoute,
  ClassIdSetSetIdQuizRoute,
  ClassIdSetSetIdClassicalRoute,
  ClassIdSetSetIdSpatialRoute,
  ClassIdSetSetIdIndexRoute,
})

const ClassIdRouteWithChildren = ClassIdRoute._addFileChildren({
  ClassIdUploadRoute,
  ClassIdAssignmentsRoute,
  ClassIdAssignmentAssignmentIdRoute,
  ClassIdIndexRoute,
  ClassIdSetSetIdRoute: ClassIdSetSetIdRouteWithChildren,
})

const MeetingIdRouteWithChildren = MeetingIdRoute._addFileChildren({
  MeetingIdIndexRoute,
  MeetingIdUploadRoute,
  MeetingIdSessionSessionIdRoute,
})

const TeacherRouteWithChildren = TeacherRoute._addFileChildren({
  TeacherIndexRoute,
  TeacherAnalyticsRoute,
  TeacherClassIdRoute,
  TeacherClassIdGradeRoute,
  TeacherClassIdAssessmentAssessmentIdRoute,
  TeacherClassIdStudentStudentIdRoute,
})

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ArchivedRoute,
  ComingSoonRoute,
  DashboardRoute,
  LoginRoute,
  ProfileRoute,
  SignupRoute,
  NotesRoute,
  MeetingsRoute,
  ProjectsRoute,
  ProjectIdRoute,
  TeacherRoute: TeacherRouteWithChildren,
  ClassIdRoute: ClassIdRouteWithChildren,
  MeetingIdRoute: MeetingIdRouteWithChildren,
  ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
