/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ClassIdRouteImport } from './routes/class.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ClassIdIndexRouteImport } from './routes/class.$id.index'
import { Route as ClassIdUploadRouteImport } from './routes/class.$id.upload'
import { Route as ClassIdSetSetIdRouteImport } from './routes/class.$id.set.$setId'
import { Route as ClassIdSetSetIdIndexRouteImport } from './routes/class.$id.set.$setId.index'
import { Route as ClassIdSetSetIdAudioRouteImport } from './routes/class.$id.set.$setId.audio'
import { Route as ClassIdSetSetIdFlashcardsRouteImport } from './routes/class.$id.set.$setId.flashcards'
import { Route as ClassIdSetSetIdQuizRouteImport } from './routes/class.$id.set.$setId.quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassIdRoute = ClassIdRouteImport.update({
  id: '/class/$id',
  path: '/class/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassIdIndexRoute = ClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassIdRoute,
} as any)
const ClassIdUploadRoute = ClassIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ClassIdRoute,
} as any)
const ClassIdSetSetIdRoute = ClassIdSetSetIdRouteImport.update({
  id: '/set/$setId',
  path: '/set/$setId',
  getParentRoute: () => ClassIdRoute,
} as any)
const ClassIdSetSetIdIndexRoute = ClassIdSetSetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassIdSetSetIdRoute,
} as any)
const ClassIdSetSetIdAudioRoute = ClassIdSetSetIdAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => ClassIdSetSetIdRoute,
} as any)
const ClassIdSetSetIdFlashcardsRoute =
  ClassIdSetSetIdFlashcardsRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => ClassIdSetSetIdRoute,
  } as any)
const ClassIdSetSetIdQuizRoute = ClassIdSetSetIdQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => ClassIdSetSetIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/class/$id': typeof ClassIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/class/$id/upload': typeof ClassIdUploadRoute
  '/class/$id/': typeof ClassIdIndexRoute
  '/class/$id/set/$setId': typeof ClassIdSetSetIdRouteWithChildren
  '/class/$id/set/$setId/audio': typeof ClassIdSetSetIdAudioRoute
  '/class/$id/set/$setId/flashcards': typeof ClassIdSetSetIdFlashcardsRoute
  '/class/$id/set/$setId/quiz': typeof ClassIdSetSetIdQuizRoute
  '/class/$id/set/$setId/': typeof ClassIdSetSetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/class/$id/upload': typeof ClassIdUploadRoute
  '/class/$id': typeof ClassIdIndexRoute
  '/class/$id/set/$setId/audio': typeof ClassIdSetSetIdAudioRoute
  '/class/$id/set/$setId/flashcards': typeof ClassIdSetSetIdFlashcardsRoute
  '/class/$id/set/$setId/quiz': typeof ClassIdSetSetIdQuizRoute
  '/class/$id/set/$setId': typeof ClassIdSetSetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/class/$id': typeof ClassIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/class/$id/upload': typeof ClassIdUploadRoute
  '/class/$id/': typeof ClassIdIndexRoute
  '/class/$id/set/$setId': typeof ClassIdSetSetIdRouteWithChildren
  '/class/$id/set/$setId/audio': typeof ClassIdSetSetIdAudioRoute
  '/class/$id/set/$setId/flashcards': typeof ClassIdSetSetIdFlashcardsRoute
  '/class/$id/set/$setId/quiz': typeof ClassIdSetSetIdQuizRoute
  '/class/$id/set/$setId/': typeof ClassIdSetSetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archived'
    | '/coming-soon'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/class/$id'
    | '/api/auth/$'
    | '/class/$id/upload'
    | '/class/$id/'
    | '/class/$id/set/$setId'
    | '/class/$id/set/$setId/audio'
    | '/class/$id/set/$setId/flashcards'
    | '/class/$id/set/$setId/quiz'
    | '/class/$id/set/$setId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived'
    | '/coming-soon'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/api/auth/$'
    | '/class/$id/upload'
    | '/class/$id'
    | '/class/$id/set/$setId/audio'
    | '/class/$id/set/$setId/flashcards'
    | '/class/$id/set/$setId/quiz'
    | '/class/$id/set/$setId'
  id:
    | '__root__'
    | '/'
    | '/archived'
    | '/coming-soon'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/signup'
    | '/class/$id'
    | '/api/auth/$'
    | '/class/$id/upload'
    | '/class/$id/'
    | '/class/$id/set/$setId'
    | '/class/$id/set/$setId/audio'
    | '/class/$id/set/$setId/flashcards'
    | '/class/$id/set/$setId/quiz'
    | '/class/$id/set/$setId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedRoute: typeof ArchivedRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ClassIdRoute: typeof ClassIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$id': {
      id: '/class/$id'
      path: '/class/$id'
      fullPath: '/class/$id'
      preLoaderRoute: typeof ClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$id/': {
      id: '/class/$id/'
      path: '/'
      fullPath: '/class/$id/'
      preLoaderRoute: typeof ClassIdIndexRouteImport
      parentRoute: typeof ClassIdRoute
    }
    '/class/$id/upload': {
      id: '/class/$id/upload'
      path: '/upload'
      fullPath: '/class/$id/upload'
      preLoaderRoute: typeof ClassIdUploadRouteImport
      parentRoute: typeof ClassIdRoute
    }
    '/class/$id/set/$setId': {
      id: '/class/$id/set/$setId'
      path: '/set/$setId'
      fullPath: '/class/$id/set/$setId'
      preLoaderRoute: typeof ClassIdSetSetIdRouteImport
      parentRoute: typeof ClassIdRoute
    }
    '/class/$id/set/$setId/': {
      id: '/class/$id/set/$setId/'
      path: '/'
      fullPath: '/class/$id/set/$setId/'
      preLoaderRoute: typeof ClassIdSetSetIdIndexRouteImport
      parentRoute: typeof ClassIdSetSetIdRoute
    }
    '/class/$id/set/$setId/audio': {
      id: '/class/$id/set/$setId/audio'
      path: '/audio'
      fullPath: '/class/$id/set/$setId/audio'
      preLoaderRoute: typeof ClassIdSetSetIdAudioRouteImport
      parentRoute: typeof ClassIdSetSetIdRoute
    }
    '/class/$id/set/$setId/flashcards': {
      id: '/class/$id/set/$setId/flashcards'
      path: '/flashcards'
      fullPath: '/class/$id/set/$setId/flashcards'
      preLoaderRoute: typeof ClassIdSetSetIdFlashcardsRouteImport
      parentRoute: typeof ClassIdSetSetIdRoute
    }
    '/class/$id/set/$setId/quiz': {
      id: '/class/$id/set/$setId/quiz'
      path: '/quiz'
      fullPath: '/class/$id/set/$setId/quiz'
      preLoaderRoute: typeof ClassIdSetSetIdQuizRouteImport
      parentRoute: typeof ClassIdSetSetIdRoute
    }
  }
}

interface ClassIdSetSetIdRouteChildren {
  ClassIdSetSetIdAudioRoute: typeof ClassIdSetSetIdAudioRoute
  ClassIdSetSetIdFlashcardsRoute: typeof ClassIdSetSetIdFlashcardsRoute
  ClassIdSetSetIdQuizRoute: typeof ClassIdSetSetIdQuizRoute
  ClassIdSetSetIdIndexRoute: typeof ClassIdSetSetIdIndexRoute
}

const ClassIdSetSetIdRouteChildren: ClassIdSetSetIdRouteChildren = {
  ClassIdSetSetIdAudioRoute: ClassIdSetSetIdAudioRoute,
  ClassIdSetSetIdFlashcardsRoute: ClassIdSetSetIdFlashcardsRoute,
  ClassIdSetSetIdQuizRoute: ClassIdSetSetIdQuizRoute,
  ClassIdSetSetIdIndexRoute: ClassIdSetSetIdIndexRoute,
}

const ClassIdSetSetIdRouteWithChildren = ClassIdSetSetIdRoute._addFileChildren(
  ClassIdSetSetIdRouteChildren,
)

interface ClassIdRouteChildren {
  ClassIdUploadRoute: typeof ClassIdUploadRoute
  ClassIdIndexRoute: typeof ClassIdIndexRoute
  ClassIdSetSetIdRoute: typeof ClassIdSetSetIdRouteWithChildren
}

const ClassIdRouteChildren: ClassIdRouteChildren = {
  ClassIdUploadRoute: ClassIdUploadRoute,
  ClassIdIndexRoute: ClassIdIndexRoute,
  ClassIdSetSetIdRoute: ClassIdSetSetIdRouteWithChildren,
}

const ClassIdRouteWithChildren =
  ClassIdRoute._addFileChildren(ClassIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivedRoute: ArchivedRoute,
  ComingSoonRoute: ComingSoonRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ClassIdRoute: ClassIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
